### ISSUE TITLE
Request: Minimize to Tray instead of Taskbar

### ISSUE THREAD

**Issue by hellfirehd** [nhmkdev/KeyCap#1]
Request: Minimize to Tray instead of Taskbar

**Comment by nhmkdev** [comment]
Good suggestion! I built a new version and caught it up with a newer SDK. See version 1.0.0.1

I opted to just never show the form in the taskbar at all. Everything can be accessed via the notification tray icon anyway.

**Comment by hellfirehd** [comment]
Awesome!  I can't wait install it.

**Comment by hellfirehd** [comment]
This is excellent! Thank you!
